### ISSUE TITLE
ComplexPattern.is_equivalent_to() requires identical bond numbering

### ISSUE THREAD

**Issue by lh64** [LoLab-VU/pysb#16]
From the code:
     # FIXME the literal site_conditions comparison requires bond numbering to be identical,
     #   so some sort of canonicalization of that numbering is necessary.

Currently, a comparison of the ComplexPatterns A(b=1)%B(a=1) and A(b=2)%B(a=2) would return False.  This needs to be fixed, especially since new code in Solver.run() uses the ComplexPattern.is_equivalent_to() method.

**Comment by alubbock** [comment]
Resolved in pysb/pysb#285
