### ISSUE TITLE
cupSODA: Make 'param_values' and 'y0' optional to conform to general simulator convention

### ISSUE THREAD

**Issue by alubbock** [LoLab-VU/pysb#26]
Issue from https://github.com/LoLab-VU/pysb-cupsoda/issues/6 originally by @lh64:

If 'y0' or 'param_values' are not passed to the CupSodaSimulator, the code should should use the values from the model and assume that they are constant for all simulations. If neither are passed, it should assume only a single simulation and maybe throw a warning.

**Comment by JamesPino** [comment]
Closing. It has already been done.
