### ISSUE TITLE
cupSODA: PySB/cupSODA example

### ISSUE THREAD

**Issue by alubbock** [LoLab-VU/pysb#29]
Issue from https://github.com/LoLab-VU/pysb-cupsoda/issues/2 originally by @lh64:

@lh64 commented on Aug 21, 2015:
Create an example (or two, or three)

@lh64 commented on Aug 29, 2015:
Created two examples, 'run_tyson_cupsoda' and 'run_egfr_tyson'. Should add some plotting commands before closing this issue.

**Comment by JamesPino** [comment]
Done. Two examples exists within examples/cupsoda
