### ISSUE TITLE
Pysb flat export

### ISSUE THREAD

**Issue by JamesPino** [LoLab-VU/pysb#35]
Doesn't output all the functions from pysb needed for the model.
When exporting the earm model, it doesn't write out to include MatchOnce.
Simple fix to add it to the file, but might be a better way to do it. Or just use from pysb import *

**Comment by alubbock** [comment]
Is the lack of `MatchOnce` the only problem? I can add it in and create a pull request if so.

It's probably better to keep the `from pysb import ...` imports explicit rather than using the `*` wildcard, in case the classes in core change in the future.

**Comment by JamesPino** [comment]
I don't know if it is only MatchOnce. I was thinking of a way to find only functions that are used. Right now it writes a list of things, even if they are used or not. For earm, Expression, Compartment, ANY, WILD are all written out but not used. Not sure if it is worth checking and only writing out what is needed? Or just add MatchOnce, plus any other functions defined in core.py that could ever be called.

**Comment by JamesPino** [comment]
It looks like MatchOnce is the only other function though. So probably best just to add that.
