### ISSUE TITLE
Improve PySB/cupSODA interface; move to separate repo

### ISSUE THREAD

**Issue by lh64** [LoLab-VU/pysb#5]
Currently, a user must construct the 'MX_0' and 'c_matrix' arrays manually and pass them to CupSODASolver.run() or run_cupsoda(). I'd like to change that so that these are created internally based on the initial conditions and parameter values of the model, also allowing for user-defined values in the method call.

**Comment by alubbock** [comment]
As per recent group meeting, cupSODA will be moved to a separate git repo.

**Comment by alubbock** [comment]
cupSODA also needs unit tests, but that will be handled in the separate repo. Hence, I'll close that ticket off in the PySB repo.

**Comment by lh64** [comment]
Issue moved to pysb-cupsoda repo
